// SUNNY MAGNET OWNER EDIT ZONE
// Normal public content, pricing, promotion display and media changes should be made here.
// Never store passwords, tokens, credentials or private partner commission rules here.

export const siteContent = {
  brand: {
    name: 'Sunny Magnet',
    nameFirst: 'Sunny',
    nameHighlight: 'Magnet',
    locale: 'Vietnam',
  },
  contact: {
    phone: '09xx xxx xxx',
    address: 'Ho Chi Minh City, Vietnam',
    supportUrl: 'https://zalo.me/',
  },
  commerce: {
    unitPrice: 20000,
    currency: 'VND',
  },
  promotion: {
    enabled: false,
    type: null,
    title: '',
    description: '',
  },
  seo: {
    title: 'Sunny Magnet — Custom Photo Magnets | Nam châm ảnh cá nhân hóa',
    description: 'Turn your memories into beautiful custom photo magnets. Fast delivery across Vietnam.',
  },
  media: {
    heroSlides: [
      '/images/sunny/hero/hero-01-fridge.webp',
      '/images/sunny/hero/hero-02-family.webp',
      '/images/sunny/hero/hero-03-wedding.webp',
      '/images/sunny/hero/hero-04-pet.webp',
      '/images/sunny/hero/hero-05-product.webp',
    ],
    heroAlt: 'Photo magnets on fridge',
    pricingImage: {
      url: '/images/sunny/sunny-pricing-final.webp',
      alt: 'Photo magnets',
    },
    gallery: [
      { url: 'https://images.pexels.com/photos/15555956/pexels-photo-15555956.jpeg', label: 'Family fridge' },
      { url: 'https://images.pexels.com/photos/15555954/pexels-photo-15555954.jpeg', label: 'Travel memories' },
      { url: 'https://images.pexels.com/photos/17210076/pexels-photo-17210076.jpeg', label: 'Sunny mornings' },
      { url: 'https://images.pexels.com/photos/2769188/pexels-photo-2769188.jpeg', label: 'Photo magnet collection' },
      { url: 'https://images.pexels.com/photos/1303087/pexels-photo-1303087.jpeg', label: 'Premium gift box' },
      { url: 'https://images.pexels.com/photos/15569097/pexels-photo-15569097.jpeg', label: 'Kitchen classics' },
    ],
  },
  labels: {
    gallery: 'Gallery',
    pricing: 'Pricing',
    howSteps: '3 steps',
    popular: 'POPULAR',
    languageToggle: 'Toggle language',
    vietQrAlt: 'VietQR',
    vietQrFallback: 'QR sẽ được gửi qua Zalo trong ít phút',
    footerMadeIn: 'Made with ☀️ in Vietnam',
  },
  translations: {
  en: {
    nav: { how: 'How it works', gallery: 'Gallery', pricing: 'Pricing', order: 'Order Now' },
    hero: {
      badge: 'Made with love in Vietnam ☀️',
      title: 'Turn your memories into',
      titleHighlight: 'sunny photo magnets',
      subtitle: 'Custom-printed, premium photo magnets that make your fridge feel like a warm hug. Upload once, smile every day.',
      cta: 'Order Now',
      ctaSecondary: 'See how it works',
      stat1: '10,000+ happy customers',
      stat2: '4.9/5 rating',
      stat3: 'Ships in 24h',
      visualBadges: {
        customTitle: 'Custom made',
        customSubtitle: 'from your photos',
        warrantyTitle: 'Product warranty',
        warrantySubtitle: '1 year',
        print: 'HD Print',
      },
    },
    features: {
      title: 'Why customers love Sunny Magnet',
      items: [
        { title: 'Premium quality', desc: 'Vivid HD printing on durable magnet sheets — no fading, no bending.' },
        { title: 'Fast delivery', desc: 'Printed and shipped nationwide within 24-48 hours.' },
        { title: 'Gift-ready packaging', desc: 'Every order arrives in a beautiful premium gift box.' },
      ],
    },
    gallery: {
      title: 'A little gallery on your fridge',
      subtitle: 'Realistic mockups — this is what your memories will look like every morning.',
    },
    pricing: {
      title: 'Simple, honest pricing',
      subtitle: 'One clear price for every magnet.',
      unit: '/ magnet',
      tiers: [
        { name: 'Photo magnet', qty: 'Any quantity', perk: 'One clear price per magnet', highlight: true },
      ],
      cta: 'Order now',
    },
    how: {
      title: 'How it works',
      subtitle: '3 sunny steps from photo to fridge.',
      steps: [
        { title: 'Upload your photos', desc: 'Drag & drop your favorite memories, right from your phone.' },
        { title: 'Preview & edit', desc: 'We help you crop, enhance and preview each magnet.' },
        { title: 'Fast delivery', desc: 'We print, pack in a premium box and ship to your door.' },
      ],
    },
    form: {
      title: 'Place your order',
      subtitle: 'Fill out the form and our team will contact you within 15 minutes.',
      name: 'Full name',
      namePh: 'e.g., Nguyen Van A',
      phone: 'Phone number',
      phonePh: 'e.g., 09xx xxx xxx',
      address: 'Shipping address',
      addressPh: 'Street, District, City',
      email: 'Email (optional)',
      emailPh: 'you@example.com',
      delivery: 'Delivery method',
      deliveryHome: 'Home delivery (fee applies)',
      deliveryPickup: 'Pick up at store (free)',
      referral: 'Referral code (optional)',
      referralPh: 'e.g., SUNNY10',
      quantity: 'Number of magnets',
      quantityHint: 'auto-counted from Magnet Studio',
      notes: 'Notes (optional)',
      notesPh: 'Anything we should know?',
      submit: 'Send my order',
      sending: 'Sending...',
      success: 'Order received!',
      error: 'Something went wrong. Please try again.',
      required: 'Please fill in name, phone, address and delivery method.',
      needMagnets: 'Please add at least 1 magnet in the Magnet Studio above.',
    },
    thankYou: {
      title: 'Thank you!',
      subtitle: 'Your order has been received.',
      orderIdLabel: 'Order ID',
      totalLabel: 'Total',
      magnetsLabel: 'magnets',
      qrLabel: 'Scan the VietQR code below to pay',
      zaloBtn: 'Chat via Zalo for support',
      newOrder: 'Place a new order',
      copyOrderId: 'Copy',
      copied: 'Copied!',
      note: 'A confirmation will be sent shortly. If anything looks off, just tap the Zalo button.',
    },
    footer: {
      tagline: 'Turning memories into magnets since 2024.',
      contact: 'Contact',
      rights: 'All rights reserved.',
    },
    stickyCta: {
      create: 'Create your magnets',
      continue: 'Continue to order',
      unitSingular: 'magnet',
      unitPlural: 'magnets',
    },
    studio: {
      badge: 'Magnet Studio',
      title: 'Design your magnets',
      subtitle: 'Upload your photos, preview them as real magnets, then fine-tune each one — crop, rotate, and pop it with a one-click filter.',
      uploadCta: 'Upload photos',
      uploadHint: 'Drop your photos here, or tap to browse',
      supported: 'JPG, PNG, HEIC • up to 20 photos',
      addMore: 'Add more',
      clearAll: 'Clear all',
      configured: 'configured',
      of: 'of',
      magnets: 'magnets',
      edit: 'Crop & Adjust',
      remove: 'Remove',
      saved: 'Saved',
      needsSetup: 'Tap to configure',
      totalReady: 'ready to print',
      empty: 'No photos yet',
      emptyDesc: 'Start by uploading a few favorite memories.',
      useThese: 'Use these magnets',
      editor: {
        title: 'Design magnet',
        zoom: 'Zoom',
        rotate: 'Rotate',
        pan: 'Drag • pinch to zoom',
        filter: 'Filter',
        bleedNote: 'The dimmed 2.5mm edge folds to the back — keep important details inside the bright 65×65mm safe area.',
        safeArea: 'Safe area • 65×65mm',
        bleed: 'Bleed • 70×70mm',
        adjustments: 'Adjustments',
        brightness: 'Brightness',
        contrast: 'Contrast',
        whiteBalance: 'White balance',
        temperature: 'Temperature',
        aiEnhance: 'AI Auto-Enhance',
        aiEnhancing: 'Analyzing…',
        filters: {
          none: 'Original',
          auto: 'Auto',
          bright: 'Brighten',
          vibrant: 'Vibrant',
          pastel: 'Pastel Pop',
        },
        reset: 'Reset',
        save: 'Save magnet',
        saving: 'Rendering…',
        cancel: 'Cancel',
      },
    },
  },
  vi: {
    nav: { how: 'Cách đặt hàng', gallery: 'Bộ sưu tập', pricing: 'Bảng giá', order: 'Đặt mua ngay' },
    hero: {
      badge: 'Sản xuất tại Việt Nam ☀️',
      title: 'Biến kỷ niệm thành',
      titleHighlight: 'nam châm ảnh rực rỡ',
      subtitle: 'Nam châm ảnh in cao cấp theo yêu cầu — biến chiếc tủ lạnh của bạn thành một góc kỷ niệm ấm áp mỗi ngày.',
      cta: 'Đặt mua ngay',
      ctaSecondary: 'Xem cách đặt',
      stat1: '10.000+ khách hàng',
      stat2: '4.9/5 đánh giá',
      stat3: 'Giao trong 24h',
      visualBadges: {
        customTitle: 'Thiết kế riêng',
        customSubtitle: 'từ ảnh của bạn',
        warrantyTitle: 'Bảo hành sản phẩm',
        warrantySubtitle: '1 năm',
        print: 'In HD',
      },
    },
    features: {
      title: 'Vì sao khách yêu Sunny Magnet',
      items: [
        { title: 'Chất lượng cao cấp', desc: 'In HD sắc nét trên nam châm dày dặn — không phai màu, không cong vênh.' },
        { title: 'Giao siêu nhanh', desc: 'In và giao toàn quốc trong 24 - 48 giờ.' },
        { title: 'Hộp quà sang trọng', desc: 'Mỗi đơn hàng đều đóng gói trong hộp quà premium.' },
      ],
    },
    gallery: {
      title: 'Một triển lãm nhỏ trên tủ lạnh',
      subtitle: 'Ảnh mockup thực tế — đây là những gì bạn thấy mỗi sáng.',
    },
    pricing: {
      title: 'Giá minh bạch, đơn giản',
      subtitle: 'Một mức giá rõ ràng cho mỗi nam châm.',
      unit: '/ nam châm',
      tiers: [
        { name: 'Nam châm ảnh', qty: 'Số lượng tùy chọn', perk: 'Một mức giá rõ ràng cho mỗi nam châm', highlight: true },
      ],
      cta: 'Đặt mua ngay',
    },
    how: {
      title: 'Cách đặt hàng',
      subtitle: '3 bước đơn giản từ ảnh đến tủ lạnh.',
      steps: [
        { title: 'Tải ảnh lên', desc: 'Kéo thả những kỷ niệm yêu thích, ngay từ điện thoại.' },
        { title: 'Xem & chỉnh sửa', desc: 'Chúng tôi giúp bạn cắt, tăng sáng và xem trước từng nam châm.' },
        { title: 'Giao hàng nhanh', desc: 'In, đóng hộp quà cao cấp và giao tận nhà.' },
      ],
    },
    form: {
      title: 'Đặt đơn hàng của bạn',
      subtitle: 'Điền thông tin và đội ngũ Sunny sẽ liên hệ trong 15 phút.',
      name: 'Họ và tên',
      namePh: 'VD: Nguyễn Văn A',
      phone: 'Số điện thoại',
      phonePh: 'VD: 09xx xxx xxx',
      address: 'Địa chỉ giao hàng',
      addressPh: 'Số nhà, đường, quận, thành phố',
      email: 'Email (không bắt buộc)',
      emailPh: 'ban@example.com',
      delivery: 'Phương thức nhận hàng',
      deliveryHome: 'Giao hàng tận nhà (Tính phí)',
      deliveryPickup: 'Nhận hàng tại Điểm bán (Miễn phí)',
      referral: 'Mã giới thiệu (không bắt buộc)',
      referralPh: 'VD: SUNNY10',
      quantity: 'Số lượng nam châm',
      quantityHint: 'tự động đếm từ Magnet Studio',
      notes: 'Ghi chú (không bắt buộc)',
      notesPh: 'Điều gì bạn muốn chúng tôi biết?',
      submit: 'Gửi đơn hàng',
      sending: 'Đang gửi...',
      success: 'Đã nhận đơn hàng!',
      error: 'Có lỗi xảy ra. Vui lòng thử lại.',
      required: 'Vui lòng điền họ tên, số điện thoại, địa chỉ và phương thức nhận hàng.',
      needMagnets: 'Vui lòng thêm ít nhất 1 nam châm ở Magnet Studio phía trên.',
    },
    thankYou: {
      title: 'Cảm ơn bạn!',
      subtitle: 'Đơn hàng của bạn đã được ghi nhận.',
      orderIdLabel: 'Mã đơn hàng',
      totalLabel: 'Tổng thanh toán',
      magnetsLabel: 'nam châm',
      qrLabel: 'Quét mã VietQR bên dưới để thanh toán',
      zaloBtn: 'Nhắn tin qua Zalo hỗ trợ',
      newOrder: 'Đặt đơn mới',
      copyOrderId: 'Sao chép',
      copied: 'Đã sao chép!',
      note: 'Xác nhận sẽ được gửi ngay. Nếu có bất kỳ thắc mắc, hãy nhấn nút Zalo bên dưới.',
    },
    footer: {
      tagline: 'Biến kỷ niệm thành nam châm từ 2024.',
      contact: 'Liên hệ',
      rights: 'Bảo lưu mọi quyền.',
    },
    stickyCta: {
      create: 'Tạo nam châm của bạn',
      continue: 'Tiếp tục đặt hàng',
      unitSingular: 'nam châm',
      unitPlural: 'nam châm',
    },
    studio: {
      badge: 'Xưởng Nam Châm',
      title: 'Thiết kế nam châm của bạn',
      subtitle: 'Tải ảnh lên, xem trước như nam châm thật, rồi tinh chỉnh từng chiếc — cắt, xoay và tăng sắc nét chỉ với một chạm.',
      uploadCta: 'Tải ảnh lên',
      uploadHint: 'Kéo thả ảnh vào đây, hoặc bấm để chọn',
      supported: 'JPG, PNG, HEIC • tối đa 20 ảnh',
      addMore: 'Thêm ảnh',
      clearAll: 'Xóa tất cả',
      configured: 'đã thiết kế',
      of: 'trên',
      magnets: 'nam châm',
      edit: 'Cắt & Chỉnh',
      remove: 'Xóa',
      saved: 'Đã lưu',
      needsSetup: 'Chạm để chỉnh',
      totalReady: 'sẵn sàng in',
      empty: 'Chưa có ảnh nào',
      emptyDesc: 'Hãy tải lên vài kỷ niệm yêu thích.',
      useThese: 'Dùng những nam châm này',
      editor: {
        title: 'Thiết kế nam châm',
        zoom: 'Phóng to',
        rotate: 'Xoay',
        pan: 'Kéo • chụm để zoom',
        filter: 'Bộ lọc',
        bleedNote: 'Phần rìa mờ sẽ được gấp ra mặt sau, vui lòng không để các chi tiết quan trọng ở đây.',
        safeArea: 'Vùng an toàn • 65×65mm',
        bleed: 'Vùng gấp • 70×70mm',
        adjustments: 'Tinh chỉnh',
        brightness: 'Độ sáng',
        contrast: 'Độ tương phản',
        whiteBalance: 'Cân bằng trắng',
        temperature: 'Nhiệt độ màu',
        aiEnhance: 'Làm đẹp tự động',
        aiEnhancing: 'Đang phân tích…',
        filters: {
          none: 'Nguyên bản',
          auto: 'Tự động',
          bright: 'Sáng hơn',
          vibrant: 'Rực rỡ',
          pastel: 'Pastel',
        },
        reset: 'Đặt lại',
        save: 'Lưu nam châm',
        saving: 'Đang kết xuất…',
        cancel: 'Hủy',
      },
    },
  },
}
}

export const translations = siteContent.translations
export const commerce = siteContent.commerce
export const promotion = siteContent.promotion
export const seo = siteContent.seo
